package sv.ues.fia.eisi.trues.ui.admin.estadisticas;

import androidx.appcompat.app.AlertDialog;
import androidx.fragment.app.DialogFragment;
import androidx.lifecycle.ViewModelProviders;

import android.app.Dialog;
import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

import lecho.lib.hellocharts.listener.ColumnChartOnValueSelectListener;
import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.Column;
import lecho.lib.hellocharts.model.ColumnChartData;
import lecho.lib.hellocharts.model.SubcolumnValue;
import lecho.lib.hellocharts.util.ChartUtils;
import lecho.lib.hellocharts.view.ColumnChartView;
import sv.ues.fia.eisi.trues.R;
import sv.ues.fia.eisi.trues.db.control.TramiteControl;
import sv.ues.fia.eisi.trues.db.control.UsuarioControl;
import sv.ues.fia.eisi.trues.db.control.UsuarioTramiteControl;

public class Estadistica2Fragment extends DialogFragment {

    private View view;
    private ColumnChartView columnChartView;
    private List<SubcolumnValue> values;
    private Context context;
    private List<Integer> cantidad;
    private List<String> nombre;
    private UsuarioControl control;
    private SharedPreferences sharedPreferences;
    private Integer idFacultad;
    private ColumnChartData data;

    public static Estadistica2Fragment newInstance() {
        return new Estadistica2Fragment();
    }

    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        // Use the Builder class for convenient dialog construction
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(), R.style.CustomAlertDialog);
        context = getActivity();
        sharedPreferences = getActivity().getSharedPreferences("login", Context.MODE_PRIVATE);
        idFacultad = sharedPreferences.getInt("facultad", -1);

        LayoutInflater inflater = getActivity().getLayoutInflater();
        view = inflater.inflate(R.layout.fragment_estadistica2, null);
        columnChartView = view.findViewById(R.id.chart);
        columnChartView.setOnValueTouchListener(new Estadistica2Fragment.ValueTouchListener());

        control = new UsuarioControl(context);
        cantidad = control.usuariosActivos(idFacultad);
        nombre = control.usuariosActivos2(idFacultad);

        generateDefaultData();

        builder.setView(view);
        return builder.create();
    }

    private void generateDefaultData() {
        int numSubcolumns = 1;
        int numColumns = cantidad.size();

        List<Column> columns = new ArrayList<Column>();
        List<SubcolumnValue> values;
        for (int i = 0; i < numColumns; ++i) {

            values = new ArrayList<SubcolumnValue>();
            for (int j = 0; j < numSubcolumns; ++j) {
                values.add(new SubcolumnValue(cantidad.get(i).floatValue(), ChartUtils.nextColor()));
            }

            Column column = new Column(values);
            column.setHasLabels(true);
            column.setHasLabelsOnlyForSelected(true);
            columns.add(column);
        }

        data = new ColumnChartData(columns);

        Axis axisX = new Axis();
        Axis axisY = new Axis();
        axisX.setTextColor(Color.BLACK);
        axisY.setTextColor(Color.BLACK);
        axisX.setAutoGenerated(false);
        axisY.setAutoGenerated(false);
        axisY.setName("Cantidad");
        axisX.setName("Trámite");
        data.setAxisXBottom(axisX);
        data.setAxisYLeft(axisY);

        columnChartView.setHorizontalScrollBarEnabled(true);
        columnChartView.setHorizontalFadingEdgeEnabled(true);
        columnChartView.setColumnChartData(data);
    }



    private class ValueTouchListener implements ColumnChartOnValueSelectListener {

        @Override
        public void onValueSelected(int columnIndex, int subcolumnIndex, SubcolumnValue value) {
            Toast.makeText(
                    getActivity(),
                    nombre.get(columnIndex) + ": " + cantidad.get(columnIndex),
                    Toast.LENGTH_SHORT
            ).show();
        }

        @Override
        public void onValueDeselected() {
            // TODO Auto-generated method stub

        }

    }

}